＃！ /usr/bin/env Python3
＃ - * - 編碼：UTF-8  - * -
”“”
測試ITRI網站爬網
首先測試如果我們可以訪問網站，則嘗試不同的方法
”“”

導入請求
來自BS4進口美麗的小組
進口JSON
導入操作系統
導入
從DateTime Import DateTime
從輸入導入dict，任何列表
進口時間

類TestItrawler：def __init __（self）：self.base_url =“ https：//www.itri.org.org.tw” self.session = requests.sessionsessionssession（） Gecko) Chrome/91.0.4472.124 Safari/537.36',            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',            'Mozilla/5.0 （x11; linux x86_64）AppleWebkit/537.36（Khtml，像Gecko一樣）Chrome/91.0.4472.124 Safari/537.36'，'Mozilla/5.0 test_connection（self） - > dict [str，任何]。響應。 STATUS_CODE，'content_length'：len（wendment.text），'headers'：dict（wendesp.headers），'condoding'：wendment..encoding} print（f“✓狀態：{wonsevy.status_code}”例外為E：結果['BASIC_GET'] = {'錯誤'：str（e）} print（f“ f”✗錯誤：{e}”）＃測試2：session and headers print（“ \ ntest 2：session and the session and the session and the session and the session and the sessive and the sessive and thress''）try：self.session.headers.headers.update（update（update） 'text/html，application/xhtml+xml，application/xml; q = 0.9，image/webp，*/*; q = 0.8'，'accept-language'：'zh-tw，zh; q = 0.9，en; q = 0.8'，c = 0.8'，caction-concept-code-conding'： '升級-Insecure-Requests'：'1'}）響應= self.session.get（self.base_url，timeout = 30）結果['session_get'] = {'status_code'：state.status_code，status_code，'content_length'content_length'：len（wesponse.text）：len（wesponse.text）狀態：{worlds.status_code}”）打印（f“ f”內容長度：{len（wendesp.text）}字符'）例外例外為e：結果['session_get'] = {'error'：str（e）} print（f“ f'✗枚舉（self.user_agents）：嘗試：headers = {'user-agent'：user_agent} worldsss.get（self.base_url，headers，headers，tumerout = 30）結果[f'user_agent_ {f'user_agent_ {i} user_agent}打印（f“✓用戶代理{i+1}：status {response.status_code}，長度{len（wendesp..text）}”）例外exexion a e：結果[f'user_agent_ {f'user_agent_ {i} {i}'] = {'error']頁面打印（“ \ ntest 4：特定頁面”）test_pages = ['/index.aspx'，'/about.aspx'，'/technology.aspx'，'/news.aspx'，'/contact.aspx'，'/caspx'，'/'/'/'，''，'/index.htex.html'/index.htex_ for page for for page for for：響應= self.session.get（url，timeout = 30）結果[f'page_ {page。

替換（“/”，“ _”）。替換（“。”，“ _”）}'] = {'status_code'：wendys.status_code，'content_length'：len（wendys.text），'url'：url'：url'：url}結果[f'page_ {page.replace（“/”，“ _”）。替換（“。”，“”，“ _”）}'] = {'error'：str（e）} print（f“ f”✗{page}：error {e}結構“”“湯= beautifulsoup（html_content，'html.parser'）分析= {'title'：soup.find（'title'）。get_text（strip = true）如果soup.find（'title）''''''，''''，'''，'meta_tags'：[]，'：[]，'links'：finks'：finks'：[]，'' []，'text_content'：''，'結構'：{}}＃提取meta在soup.find_all（'meta'）中的meta標籤：分析['meta_tags']。湯中的鏈接的提取鏈接。 img in Soup.find_all（'img'）：分析['image']。附加（{'src'：img.get（'src'，''），'alt'：img.get（'alt'，''，''），'title'：img.get（'img.get（'title''，'''，''''''''''''''，'''''） '動作'：form.get（'action''），'方法'：form.get（'方法'，''），'id'：form.get（'id''，''），'class'：''.join（form.get（'class'class''，[]}） script.get（'src'，''），'type'：script.get（'type''，''），'content_length'：len（script.get_text（）））＃在soup.find_all（'style'）中的樣式提取樣式的提取樣式：分析['sallays ['styles']。分析['text_content'] = soup.get_text（saparator ='\ n'，strip = true）＃分析結構分析['結構'] = {'headerings'：len（soup.find_all（['h1'，'h1'，'h2'，'h2'，'h3'，h3'，h4'，'h4'，h5'，'h5''，h6''，h6''，''''' “列表”：len（湯。 dict [str，任何]：“”“從html”中提取任何工作內容。 '表格'：[]，'links'：[]}＃提取title title_tag = soup.find（'title'）如果title_tag：content ['title''= title_tag.get_text（trip_get_text（strip = true））

content ['main_text'] = main_content＃提取導航鏈接nav_links = [] link in soup.find_all（'a'，href = true）中的鏈接：href = link.get.get（'href'，'href'，''''）text = link.get_text（strip = true）If text and text and text and text and href and href：nav_links.append off： link.get('title', '')                })        content['links'] = nav_links                # Extract forms        forms = []        for form in soup.find_all('form'):            forms.append({                'action': form.get('action', ''),                'method': form.get('method', ''),                'inputs': [{'name': inp.get('name', ''), 'type': inp.get（'type'，''）} for for Inp in form.find_all（'input'）]}）content ['forms'] = form return返回內容def content def save_test_results（self，test_ results：dict [dict [str，and ny]，分析，分析，分析，分析：dict [str，任何]，任何]，任何]，contem： “/mnt/hdd2/he110/linly-talker/llm_chat/itri_museum_docs/itri_test_data”）：“”“”““將測試結果保存到文件”“” os.makedirs（os.makedirs（uptive_ok = uptound_ok = umput_ok = true）＃與Open（OPENT oputS opent oppation ofting（optate）test test test test test test test test test test test test test _join（oft）編碼='utf-8'）作為f：json.dump（test_results，f，suse_ascii = false，縮進，縮進= 2）＃與Open（OS.Path.Join（output_dir，'content_analysis.json'），'w'），'w'，'w'，exoding ='utf-8'aS aS as s as ascess fequest，f：asscect，f insection = sublationde = aSANISS f：ascass f：secass f：saperion，打開（os.path.join（output_dir，'extract_content.json'），'w'，編碼='utf-8'）作為f：json.dump（content，f，unsue_ascii = false，suse_ascii = false，subsent = false，縮進= 2）＃保存可讀的摘要，with open（op.path.join（os.dath.join） f：f.write（“ itri網站測試結果\ n”）f.write（“ =” * 50 +“ \ n \ n”）f.write（“連接測試：\ n”）f.write（“  - ” * 20 +“ \ n”）用於test_name，test_ressss.items（f.rite test_name test_name in test_resss.items（）： f.write（f“ error：{結果['錯誤']} \ n”）else：f.write（f“ status：{result.get（'status_code'，'n/a''n/a'）} \ n”）f.write（f“ content Lengthe：result.get（result.get（result.get）分析：\ n”）f.write（“  - ” * 20 +“ \ n”）f.write（f“ title：{amalive.get（'titter'，'n/a'）} \ n”）f.write（f“ meta tags：f” meta tags：{len（amanagion.get（andaighte.get） {len（Analivals.get（'links'，[]））} \ n“）f.write（f”圖像：{len（andrace.get（'image'，[]）} \ n“）f.write（f” forms：f” forms：{len（amanagion.get（amanagion.get（'forms'forms''forms''，[]）} \ n” scriptss（'forms'n'' []））} \ n“）f.write（f”文本內容長度：{len（andrace.get（'text_content'，''，''））} \ n“）f.write（“ \ n structure：\ n”）用於key，in Analivaly.get（'strucation.get（'struction'，struction'，}）。帶有打開（OS.Path.join（output_dir，'text_content.txt'）的文本內容，'w'，w'，engoding ='utf-8'）as f：f.write（“提取文本內容\ n”）f.write（“ =” * 50 +“ \ n”） open（os.path.join（output_dir，'links.txt'），'w'，編碼='utf-8'）as f：f.write（“找到鏈接\ n”）f.write（“ =” 50 +“ \ n \ n \ n”）in content.get.get（'links'links'，[links'，'f.write（f.write（f.write）（f.write（f.write）， ''）}} \ n“）f.write（f” href：{link.get（'href'，''）} \ n“）f.write（f” title：{link.get.get（'title''，''）} \ n”）

f.write（“  - ” * 30 +“ \ n”）print（f“測試結果保存為：{output_dir}/”）print（“創建文件：”）print（“  -  test_results.json”）print（“  -  content_analysis.json”）print（“  -  content_analysis.json”）print（“ -dract_content.json”） print（“  -  links.txt”）def run_tests（self，output_dir：str =“/mnt/hdd2/he110/linly-talker/linly-talker/llm_chat/itri_museum_docs/itri_test_test_data”） test_results = self.test_connection（）＃獲取最佳工作響應best_response = none best_content_length = 0對於test_name，test_results.items（）結果：如果'error'nof result和result and.get（'status_code'status_code'== 200：content_lents'）                    best_content_length = content_length                    best_response = result                if best_response:            print(f"\n✓ Found working response with {best_content_length} characters")                        # Get the actual HTML content            if 'session_get' in test_results and 'error' not in test_results['session_get']:                response = self.session.get(self.base_url, timeout=30) html_content = worlds.text else：worldsy = requests.get（self.base_url，timeout = 30）html_content = worldsion.text.text＃分析內容分析= self.analyze_content（html_content（html_content）（html_content）＃            self.save_test_results(test_results, analysis, content, output_dir)                        print(f"\n✓ Content Analysis:")            print(f"  - Title: {analysis.get('title', 'N/A')}")            print(f"  - Links found: {len(analysis.get('links', []))}")            print(f"  - Text content: {len(analysis.get('text_content', ''))} characters")            print(f"  - Structure: {analysis.get('structure', {})}")                    else:            print("\n✗ No working responses found")            # Save test results anyway            self.save_test_results(test_results, {}, {}, output_dir)

def main（）：
crawler = testitrawler（）
crawler.run_tests（）

如果__name__ ==“ __ -main __”：
主要的（）