＃！ /usr/bin/env Python3
＃ - * - 編碼：UTF-8  - * -
”“”
Itri英語Wikipedia綜合軌
爬網iTri Wikipedia頁面的英文版本並提取所有信息
”“”

導入請求
來自BS4進口美麗的小組
進口JSON
導入操作系統
導入
從輸入導入dict，任何列表
從DateTime Import DateTime

類itrienglishCrawler：def __init __（self）：self.base_url =“ https：//en.wikipedia.org/wiki/wiki/industrial_technology_technology_research_institute self.session” self.Session = request = requestSession = selfsession（）self.session.head.head.head.update（） win64; x64）AppleWebkit/537.36（Khtml，像壁虎一樣）Chrome/91.0.4472.124 Safari/537.36'}）deffetch_page（self） -  self） - > str-> str-> str響應= self.session.get（self.base_url，timeout = 30）響應。 RAISE_FOR_STATUS（）print（“成功獲取英語Wikipedia頁面”）返迴響應。 text exts.text extcext extcept extect e：frats（f“錯誤獲取頁面：{e}”從英語wikipedia頁面“”“”“”打印（“從英語頁面中提取全面內容...”）soup = beautifulsoup（html_content，'html.parser'）＃找到主要內容div content_div = soup_div = soup.find（'div'，'iD''，'id''：'mw-content-text'; 'metadata'：{'source_url'：self.base_url，'語言'：'英語'，'crawl_timestamp'：dateTime.now（）。isoformat（）。 [],            'references': [],            'external_links': [],            'categories': [],            'raw_text': ''        }                # Extract infobox        self._extract_infobox(soup, data)                # Extract all sections        self._extract_all_sections(content_div, data)                # Extract all tables        self._extract_all_tables(content_div, data)                # Extract all lists self.__extract_all_lists（content_div，data）＃提取引用和外部鏈接self.__extract_references_and_links（湯，湯，數據）＃提取類別self._extract_categories（湯，數據）＃提取raw text self.__extract_raw_traw_traw_traw_text（content_div，content_div，data） len（數據['章節']）數據['metadata'] ['total_content_length'] = len（data [data ['raw_text']）返回數據deg _extract_infobox（self，soup，soup，soup，soup，data：dict [dict [dict [str，Any]）：如果Infobox：InfoBox_Data = {}行= infobox_data = ford_find_all（'tr'），soup.find（'table'，{'class'：'infobox'}）對於行中的行= cell.cell..find_all（['th'，'td'，'td']）If Len（Cells> cells = 2：cell = 2：cell = cell = cell = cell = 2： cells[1].get_text(strip=True)                    if key and value:                        infobox_data[key] = value                        data['infobox'] = infobox_data            print(f"Extracted {len(infobox_data)} infobox items")        else:            print("No infobox found")        def _extract_all_sections(self, content_div: BeautifulSoup, data: Dict[str, ]）：“”“”及其內容的所有部分提取所有部分。 'p'，'ul'，'ol'，'table'，'div']）：if element.name在['h1'，'h2'，'h2'，'h3'，'h4'，'h4'，'h5']中：

# Save previous subsection                if current_subsection and subsection_content:                    if current_section not in sections:                        sections[current_section] = {}                    elif isinstance(sections[current_section], str):                        # Convert string to dict if needed                        sections[current_section] = {}                    sections[current_section][current_subsection] = '\ n'.join（subsect_content）＃保存上一節，如果current_section和current_content，而不是current_subsection：部分[current_section] ='\ n'.join（current_content）heading_text = element.get_text = elemt.get_text（strip = true） = heading_text current_content = [] current_subsection = none sublect_content = [] print（f“找到主要部分：{heading_text}”）else：＃subsect current_subsection = heading_text subsection_content_content_content_content_content = []                    if current_subsection:                        subsection_content.append(text)                    else:                        current_content.append(text)                # Save last section and subsection        if current_subsection and subsection_content:            if current_section not in sections:                sections[current_section] = {}            elif isinstance(sections[current_section], str):                # Convert string to dict if needed                sections[current_section] = {}部分[current_section] [current_subsection] ='\ n'.join（subsection_content）elif current_section_section and current_content：sections [current_section] ='\ n'.join（current_content） _extract_all_tables（self，content_div：beautifulsoup，data：dict [str，任何]）：“”“提取所有表格及其數據”“”“”“ print（“提取所有表...”）表格中的表= [] table.find_all（'th'）如果標題：table_data ['headers'] = [h.get_text（strip = true）f in Headers中的h]＃提取行行= table.find_all（'tr'）in Rows in Rows in Rows：cells = cells = row.find_all（row.find_all（td'td'th'th't'tr'cyl.get_ cell.get_getA） table_data ['row']。附錄（row_data）如果table_data ['row']：tables.append（table_data）data ['table'] =表print（f“ frested {f”提取{len（tables）} pable {len（tables）} pabs} def_extrack_all_all_allists（def_extract_all_lists）且未排序）“”“” print（“提取所有列表...”）lists = []＃ul in content_div.find_all（'ul'）中的UL列表：li.find_all（'li'）（'li'）in li li of ul.find_all（'li'）：li.items = [] “無序”，“項目”：list_items

}）＃content_div.find_all（'ol'）中的OL的排序列表：li.find_all（'li'）中的li lies_items = [] = lists        print(f"Extracted {len(lists)} lists")        def _extract_references_and_links(self, soup: BeautifulSoup, data: Dict[str, Any]):        """Extract references and external links"""        print("Extracting references and external links...")                # Find references section        ref_section = soup.find('ol', {'class': 'references'})        if ref_section：ref_section = []對於ref_section.find_all（'li'）：text = ref.get_text（strip = true），如果文本：references.append（text）data ['references''] = references'= references'= references'dracted（f“提取{len（reverences）} 'mw-content-text'}）如果ext_links_section：externe_links = [] for ext_links_section.find_all（'a'a'，href = true）中的鏈接：href = link.get.get（'href'，'''）如果鏈接。類別“” print（“提取類別...”）類別= [] cat_links = soup.find_all（'a'，href = re.compile（r'/wiki/類別：'）用於cat_links中的鏈接：text_links：text = text = link.get.get.get_text（strip_text（strip = true）if text：categent if text：expend（append（append）類別）類別”）def _extract_raw_text（self，content_div：beautifulsoup，data：dict [str，任何]）：“”“提取整個乾淨的文本內容”“” print（“提取原始文本內容...”）＃刪除content_div.div.div.find_all中不需要的元素emoce_div.find_all（[ content_div.get_text(separator='\n', strip=True)                # Clean up the text        raw_text = re.sub(r'\n+', '\n', raw_text)        raw_text = re.sub(r'\s+', ' ', raw_text)                data['raw_text'] = raw_text        print(f"Extracted {len(raw_text)} characters of raw文本“）def save_as_text_files（self，數據：dict [str，任何]，output_dir：str =“//mnt/hdd2/he110/linly-tally-talker/llm_chat/itri_museum_docs/itri_english_english_english_data”）帶有open的元數據（OS.Path.join（output_dir，'metadata.txt'），'w'，endoding ='utf-8'）as f：f.write（“ itri英語wikipedia metadata \ n”） f.write（f“ {key}：{value} \ n”）＃保存Infobox with open（os.path.join（output_dir，'infobox.txt'），'w'），'w'，encoding ='utf-8'）f：f.write（f.write）在data ['infobox']。項目（）中：f.write（f“ {key}：{value} \ n”）＃與open（os.path）保存截面。

join（output_dir，'sections.txt'），'w'，sonding ='utf-8'）作為f：f.write（“ itri英語wikipedia pections \ n”）f.write（“ =” * 50 +“ \ n \ n”）for data name in data name in data name，data name，data name，data [''''exect''exect'''''''''''''''''''''''''''''' {section_name} \ n“）f.write（“  - ” * 30 +“ \ n”）如果ISInstance（content，dict）：對於subsexts_name，content.items（）中的subsexent_content（）：f.write（f.write（f“ f” \ n ###### “ \ n”）＃與open（os.path.join（output_dir，'tables.txt'），'w'，encoding ='utf-8'）的保存表為f：f.write（“ itri英語wikipedia tak \ n”） f.write（f“ \ ntable {i + 1}：\ n”）f.write（“  - ” * 20 +“ \ n”）如果表['headers']：f.write（“ headers：” +“ +” |“ .join（table [table ['headers'headers'headers']）列錶帶有open（OS.Path.join（output_dir，'lists.txt'），'w'，編碼='utf-8'）為f：f.write（“ itri English wikipedia lists \ n”）f.write（“ =” * 50 +“ \ n”）for i，list_data in en eNumElase（eNumeres） f.write（f“ \ nlist {i + 1}（{list_data ['type']}）：\ n”）f.write（“  - ” * 30 +“ \ n”）in List_data ['items']：f.write（f.write（f.write）（f.write（f”•for）（f“•{item} item} \ n”） 'w'，編碼='utf-8'）作為f：f.write（“ itri英語wikipedia參考\ n”）f.write（“ =” * 50 +“ * 50 +” \ n \ n \ n”），ref In Enumerate（data ['references'reforence']打開（OS.Path.join（output_dir，'external_links.txt'），'w'，sonding ='utf-8'）為f：f.write（“ itri English wikipedia wikipedia wikipedia外部鏈接\ n”）f.write（“ =” * 50 +“ \ n \ n”），以在數據中鏈接到data [\ n \ n》中。{link ['text']}：{link ['url']} \ n“）＃與open（OS.Path.join（outpation_dir，'categories.txt'），'W'，'W'，編碼='utf-8'）作為F：在數據['類別']中：f.write（f“•{catentory} \ n”）＃與open（OS.Path.join（output_dir，'raw_text.txt'），'w'），'w'，編碼='utf-8'）作為f： f.write（數據['raw_text']）＃與Open（OS.Path.Join（output_dir，'commistion_data.json'），'w'），'w'，encoding ='utf-8'）作為f：json.dump（data，data，f，suse_asci = false，intect = 2）upp ose_jo Joine（uspent''（upptript）， 'w'，編碼='utf-8'）作為f：f.write（“ itri英語wikipedia crawl摘要\ n”）f.write（“ =” * 50 +“ \ n \ n \ n”） {data ['metadata'] ['語言']} \ n”）f.write（f“ crawl timestamp：{data [data ['metadata'] ['crawl_timestamp']} \ n”） {data ['metadata']] ['total_content_length']}字符\ n”）f.write（f“ infobox項目：{len（data ['infobox']）} \ n”）f.write（f“表： {len（data ['lists']）} \ n“）f.write（f”引用：{len（data ['references']）} \ n“）f.write（f“外部鏈接：{len（data [data ['external_links'']）} \ n”）f。

write（f“類別：{len（data ['類別']）} \ n”）print（f“將所有數據保存到：{output_dir}/”）print（“創建文件：”）print（“  -  metadata.txt”） refuteness.txt“）print（“  -  external_links.txt”）print（“  -  categories.txt”）print（“  -  raw_text.txt”）print（“  -  commention_data.json”）print（“  -  summary.txt”）def crawl（self，uppute_dir = stry = stry = stry = stry = stry = stre = stre = “/mnt/hdd2/he110/linly-talker/llm_chat/itri_museum_docs/itri_english_data”）：“”““主要爬行方法”“”“” print（“啟動全面的itri itri itri itri itri Itri wikipedia wikipedia wikipedia wikipedia wikipedia crawler ...”內容數據= self.extract_all_content（html_content）＃保存到文件self.save_as_text_files（數據，output_dir）＃打印摘要print（“ \ n” +“ =” 50）print（“ crawl print成功完成！”打印（f“  - 語言：{data ['metadata'] ['語言']}”）print（f“找到 - 找到的章節：{data ['metadata'] ['total_sections'}）print（f“  - 內容長度：f”  -  content Length：{data [data ['metAdata''total_content']

def main（）：
crawler = itrienglishCrawler（）
data = crawler.crawl（）

如果__name__ ==“ __ -main __”：
主要的（）